apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vs
spec:
  gateways:
    - istio-system/argo-rollouts-gateway
  hosts:
    - {{ .Values.host }}
  http:
    - name: preview
      match:
        - headers:
            x-preview:
              exact: "true"
      route:
        - destination:
            host: {{ .Values.appName }}-preview
            port:
              number: 80

    - name: primary
      route:
        - destination:
            host: {{ .Values.appName }}
            port:
              number: 80
